### ISSUE TITLE
Add adding arguments when creating NSP forwarder

### ISSUE THREAD

**Issue by nriver007** [shadow2560/Ultimate-Switch-Hack-Script#6]
as title says, would love the ability to add additional arguments when creating an nsp forwarder

**Comment by shadow2560** [comment]
I've tried something but I can't test, I've added this only for NRO forwarders cause Retroarch forwarders probably don't need this. Try it and tell me if it's what you want.

**Comment by cccccraneo** [comment]
Just tested it generating a .nsp for Moonlight-Switch using arguments and the only problem I encountered appeared if I tried to generate the .nsp thru the GUI option: 

> "control\control.nacp file missing in script's folder"


Other than that no problems at all! Thanks for your hard work! 👍

**Comment by shadow2560** [comment]
> Just tested it generating a .nsp for Moonlight-Switch using arguments and the only problem I encountered appeared if I tried to generate the .nsp thru the GUI option:
> 
> > "control\control.nacp file missing in script's folder"
> 
> Other than that no problems at all! Thanks for your hard work! 👍

Thanks for your report. I've tried to fix the GUI in version 4.3.344, it should work now.

**Comment by nriver007** [comment]
GUI version still shows the same error using current master build.

CLI works great! thank you!! just what I wanted and might be the only actually working NSP forwarder (with or without arguments) for the current switch version (V19.0.0), as I tried multiple others and nothing worked.

**Comment by shadow2560** [comment]
GUI should work now, I've tested the creation without problem (install not tested).
